### ISSUE TITLE
Question: _update.mid files

### ISSUE THREAD

**Issue by DemirHerif** [rjkiv/rb3_plus#1]
Some MIDI files has _update.mid format. How I install these files and what's the difference from others? If I rename with _plus, is it works like same?

**Comment by rjkiv** [comment]
Whoops, I pushed some update midis for RB3DX instead of just the harmony midis. Give me a moment, and I'll push the proper _plus midis.

**Comment by DemirHerif** [comment]
I've write before, maybe you've not see it... do you have plans the release a harmony for a forbidden song, Miley Cyrus - Party In The USA? It doesn't have any harmonies, because this DLC has released and delisted after a few hours.

**Comment by rjkiv** [comment]
There, the affected midi files have been fixed.

For installation, I would really honestly recommend installing [RB3 Deluxe](https://github.com/jnackmclain/rock-band-3-deluxe), as all of these harmonies are built into that project. Installing one individual harmony file is a lengthy and involved process, so going the RB3DX route would save you a lot of time as well as potential troubleshooting-induced headache.

Regarding Party in the USA - I do plan to *eventually* author harmonies for them, but it's a little low down the queue. I don't really take requests for what I chart, I just chart whatever I feel like, when I feel like it.
