### ISSUE TITLE
Rock band 1 songs work but not rock band 2?

### ISSUE THREAD

**Issue by GucciGuwop420** [rjkiv/rb3_plus#11]
Platform: Vanilla Xbox 360
So i downloaded all the rock band 1 and 2 on disc con files then downloaded the harmony upgrades for the songs. I used the C3 con tools to upgrade the songs then put the new (bundled) songs on my flash drive with RBtoUsb. I already had all these Con files (non bundled songs from rock band 1 and 2) on my xbox and so i just moved the new ones over and cleared the song cache on Rock band 3 but only the rock band 1 songs had the harmony upgrades.

**Comment by GucciGuwop420** [comment]
Also im on the regular rock band 3 and TU4.

**Comment by rjkiv** [comment]
If you look in the RB2 songs' dta files, does each upgraded song contain the line (vocal_parts X)?

**Comment by GucciGuwop420** [comment]
it says vocal parts 3

**Comment by rjkiv** [comment]
Just tried doing this on my RGH 360 and the songs show up fine. I'd say this is an issue with your 360 being vanilla.

**Comment by GucciGuwop420** [comment]
ok ill try deleting my song cache again.
