### ISSUE TITLE
Rock Band 1 songs not showing up in Rock Band 2

### ISSUE THREAD

**Issue by GucciGuwop420** [rjkiv/rb3_plus#12]
Im on a regular xbox
I downloaded all the on disc rock band 1 songs with unexportables and the licence transfer key from the google drive and they show up in rock band 3 but not in rock band 2. 
I used C3 con tools to to put it on my xbox.
I was wondering if i need to reformat the file for the songs to show up in rock band 2. I also deleted the rock band 2 song cache and they still dont show up.

**Comment by jnackmclain** [comment]
Enable contpatch in dash launch. Also this repo has precisely 0% to do with this at all.

**Comment by rjkiv** [comment]
^
