### ISSUE TITLE
Not all Harmonies upgrades showing up in game

### ISSUE THREAD

**Issue by GucciGuwop420** [rjkiv/rb3_plus#15]
Im playing on vanilla xbox 360 using the c3 con tools to upgrade the songs and some of the harmony upgrades show up in game and some don't. The songs im upgrading are dlc not exports. I even deleted the song cache and one of the harmonies disappeared after doing that. Any help would be appreciated.

**Comment by rjkiv** [comment]
Do you have any official pro string upgrades on your console? Those can conflict with harmonies (i.e. Under the Bridge may not have harmonies show up if you have the pro upgrade)

**Comment by GucciGuwop420** [comment]
No I don’t have any string upgrades.

**Comment by GucciGuwop420** [comment]
Do any upgrades affect it or just ones for the song?
