### ISSUE TITLE
Missing songs for pro keys.

### ISSUE THREAD

**Issue by GucciGuwop420** [rjkiv/rb3_plus#17]
Im looking for legacy songs that had keys added to them like "Dont stop [believin] (https://www.youtube.com/watch?v=HDS-3novu2g) " and "[foreplay/longtime] (https://www.youtube.com/watch?v=pTxjt99neVQ)" from the rock band harmonies project. I have rb3dx on my rgh but only a couple legacy songs have keys.

**Comment by rjkiv** [comment]
The reason these songs aren't in rb3_plus (and by extension, RB3DX) is because I want my pro key upgrades to have dedicated key stems too, not just a key chart. Sure, that means I'm way more limited in my key upgrades versus RBHP's, but having separate key audio makes the upgrade feel "complete".
