### ISSUE TITLE
Question: New RB4 Harmony Upgrades to RB3

### ISSUE THREAD

**Issue by DemirHerif** [rjkiv/rb3_plus#4]
Some songs in RB3 has received harmony upgrades in RB4, but these upgrades are not available in RBHP or RB3 Deluxe. For example; In This Moment - Mechanical Love. Maybe we can implement these upgrades to RB3 too?

**Comment by rjkiv** [comment]
This issue is on the backlog, and will get done eventually, just like the remaining forbidden harms
