### ISSUE TITLE
so far away crash

### ISSUE THREAD

**Issue by trishiskukky** [rjkiv/rb3_plus#71]
playing So Far Away by Avenged Sevenfold on pro guitar leads to a crash :/

**Comment by Aloquendiar** [comment]
yep, we just checked it with camilo and when choosing guitar pro the game crashes

**Comment by rjkiv** [comment]
Magma didn't find any issues with the chart, and double checking the midi itself, and the trainers (the one thing magma doesn't seem to check) look fine too

**Comment by rjkiv** [comment]
confirmed to be a 3DX issue
