### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Eladodo** [rjkiv/rb3_plus#9]
hey guys 
i try to install the any way you want it upgrade and its not show up to me when i go to the song in rock band 3 
please help me fix this

**Comment by jnackmclain** [comment]
For future reference, when creating a github issue, you should include
Platform: Xbox or PS3
The steps you used to install the song
Did you clear your song cache on Xbox?
Are you playing Deluxe?

The best and easiest method to play rb3_plus songs is to play [Rock Band 3 Deluxe](https://github.com/hmxmilohax/rock-band-3-deluxe) which incorporates rb3_plus upgrades by default, no DLC editing required.

**Comment by Eladodo** [comment]
Hi Sorry about that didn’t know , I am using xbox 360 . I will try to delete the song cache and see if its working I don’t if i have deluxe but I will let you knowThanks for respondנשלח מה-iPhone שלי‫ב-8 בדצמ׳ 2022, בשעה 19:22, ‏‏jnack ***@***.***> כתב/ה:‬﻿
For future reference, when creating a github issue, you should include
Platform: Xbox or PS3
The steps you used to install the song
Did you clear your song cache on Xbox?
Are you playing Deluxe?
The best and easiest method to play rb3_plus songs is to play Rock Band 3 Deluxe which incorporates rb3_plus upgrades by default, no DLC editing required.

**Comment by Eladodo** [comment]
Still not working after i clean the song cacheAny help?נשלח מה-iPhone שלי‫ב-8 בדצמ׳ 2022, בשעה 21:07, ***@***.*** כתב/ה:‬﻿Hi Sorry about that didn’t know , I am using xbox 360 . I will try to delete the song cache and see if its working I don’t if i have deluxe but I will let you knowThanks for respondנשלח מה-iPhone שלי‫ב-8 בדצמ׳ 2022, בשעה 19:22, ‏‏jnack ***@***.***> כתב/ה:‬﻿
For future reference, when creating a github issue, you should include
Platform: Xbox or PS3
The steps you used to install the song
Did you clear your song cache on Xbox?
Are you playing Deluxe?
The best and easiest method to play rb3_plus songs is to play Rock Band 3 Deluxe which incorporates rb3_plus upgrades by default, no DLC editing required.

**Comment by Eladodo** [comment]
hi it does load the content of the song in game it says before 2 of 2 loaded but when i load the song the pro upgrade not show up you know what can be the problem?

**Comment by jnackmclain** [comment]
I'd just recommend installing rock band 3 deluxe at this point honestly. Much smoother than editing your dlc files

**Comment by Eladodo** [comment]
i just want the pro mode for this song honestly and i have a lot of content and a lot of songs in rock band 3 thats on my xbox so i prefer not to do that just to understand what am i doing wrong with those pro upgrades

**Comment by jnackmclain** [comment]
You haven't told me what you did so I can't really point where you went wrong.

**Comment by Eladodo** [comment]
ok so i will explain you i try install the any way you want it pro upgrade i follow all the steps and boot up the game and its says that there is new content (i mean in the loading screen it loads it and says 2 out of 2 files like when you adding a custom or any dlc) but when i go to the song i didnt see any upgrades thats added to the song so i dont know what to do

**Comment by jnackmclain** [comment]
Are you sure your upgrades.dta is correct with the any way you want it song data, including ranks for real_guitar?
And your songs folder is named songs_upgrades
Not showing the rank indicates a dta problem, as that's how it shows on the setlist. You also need to delete your song cache, located next to your save file, every time you add pro additions or when testing this.

**Comment by jnackmclain** [comment]
After installing the upgrade, before loading the game, delete your song cache.

I told you, check for rank real_guitar in the dta file in the con you built.
Make sure the layout is the same as the readme image in this repo, and check the dta inside the con you created and make sure it has a rank in real_guitar.
You should probably post a screen shot of your setup.

**Comment by Eladodo** [comment]
so i need to put the update in the file then delete the song cashe? 
And what is this file ? who do i find it ? I have anywayyouwantit_plus.mid and upgrades.dta

**Comment by Eladodo** [comment]
![image](https://user-images.githubusercontent.com/120120703/206736565-cb89d630-66f3-49ef-85f7-fc4f95b00742.png)

**Comment by jnackmclain** [comment]
Why aren't you using c3 con tools as stated in the readme? Following the readme exactly will get this working. Otherwise, I'm going back to my original response at this point and telling you to just install rb3 deluxe. It won't ruin any of your installed content, I'm unable to help you further.

**Comment by Eladodo** [comment]
ok my friend i will try try again later thank you for your help

**Comment by Eladodo** [comment]
![image](https://user-images.githubusercontent.com/120120703/206794993-c3773235-b4ac-4a50-9e5d-69be29145786.png)

**Comment by Eladodo** [comment]
hi my friend , what should i do from this screen? and did i made the con file correct?

**Comment by rjkiv** [comment]
Per the README, once you have the file structure down, you have to save the file as LIVE instead of CON.
